### ISSUE TITLE
Valve entity error log

### ISSUE THREAD

**Issue by Joao-Sousa-71** [rgc99/irrigation_unlimited#159]
I recently add a water timer controller that use two valve entities. And with this configuration:

`irrigation_unlimited:
  granularity: 60
  refresh_interval: 30
  controllers:
    - name: 'Rega Horta e Plantas'
      zones:
        - name: Rega Horta
          entity_id: valve.dual_water_timer_wt05_rega_horta_valve_1
          show: # <= Add these two lines to the       
            timeline: true # <= configuration for individual zones
          schedules:
            - time: "08:00"
              duration: "00:03:00"
              month: [apr, may, oct]     
`
I get the following error:

`2024-04-27 00:51:25.166 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_off does not support entities valve.dual_water_timer_wt05_rega_horta_valve_1`

Is this supported?

https://www.home-assistant.io/integrations/valve/#valve-control-services

Or I should open a feature request.
Thank you very much.

**Comment by evercape** [comment]
The [documentation](https://github.com/rgc99/irrigation_unlimited?tab=readme-ov-file#143-switch-entities) does state 

> These can be any entity from the switch or light platforms or anything that supports the turn_on and turn_off actions. 

So in theory that may work. Home assistant introduced [valves](https://www.home-assistant.io/integrations/valve/) with the [Jan 2024 release](https://www.home-assistant.io/blog/2024/01/03/release-20241/#new-entity-type-valve) only, so that may require an update on the irrigation unlimited switch entity.

I am running everything on [KNX](https://www.home-assistant.io/integrations/knx/) so I am waiting for a `valve` device type to then adapt my switches to it.

@rgc99 can you maybe check if device type `valve` is supported? If not it should be relatively easy to integrate as you already support `switch` and `light` device type. Thanks!

**Comment by Joao-Sousa-71** [comment]
@evercape I tried in the developer tools to use the homeassistant.turn_off with a valve entity and it fails. The service to be used must be valve.close (and valve.open). I'm not sure if this fits as a bug but maybe as a feature request since as you mentioned the valve entities are quite new in HA.

**Comment by evercape** [comment]
yes good point. I am sure it's simple to add.

For those on KNX I have [requested](https://community.home-assistant.io/t/need-the-new-valve-especially-for-the-knx-plattform/666090/3) to add valve type to KNX as well.

**Comment by rgc99** [comment]
The valve domain is not currently supported. A work around is to track the state with an automation similar to what is shown in the [documentation](https://github.com/rgc99/irrigation_unlimited#143-switch-entities) for a cover. You might also be able to create a switch type alias for the valve but I am not sure on this.

Best to handle it natively. Please open a feature request.

**Comment by Joao-Sousa-71** [comment]
Feature request opened.
