### ISSUE TITLE
Is there an alternative for Average Sensor planned?

### ISSUE THREAD

**Issue by hvorragend** [rgc99/irrigation_unlimited#66]
**Is your feature request related to a problem? Please describe.**
With HA Core 2022.5.x we have several problems with the Average Sensor (https://github.com/Limych/ha-average).
There was a workaround to get this custom component running again.
But as far as I know this is just a "quick&dirty"-fix.

You are using the sensor in https://github.com/rgc99/irrigation_unlimited/blob/master/packages/irrigation_unlimited_adjustment.yaml.

Is it planned to switch a another calculation method?

**Describe the solution you'd like**
Is it possible to use a filter sensor? 
Or the statistics sensor?

**Additional context**
I think that this could be quite difficult, because in other sensors we don't have the possibility to use a "start" and an "end".

**Comment by rgc99** [comment]
I think the fix is ok but there is more work to be done regarding the "Detected integration that accesses the database without the database executor" message. I encountered this same message in my own integration and are currently testing out some changes. The main issue is the fetching needs to be done asynchronously.

I don't see an immediate replacement for this integration. It is quite flexible with the date ranges being able to pluck periods like last hour, yesterday etc. Hopefully it will get some attention. For now it is working.

**Comment by hvorragend** [comment]
Thanks for your assessment.
